### ISSUE TITLE
Move solvation work-around here? 

### ISSUE THREAD

**Issue by davidlmobley** [oess/oeommtools#11]
I'm in a place where I'm needing to duplicate the code here https://github.com/oess/openmm_orion/blob/master/ComplexPrepCubes/utils.py#L108-L152 for a different problem. What about moving this (or even the whole `solvate` function there) into `oeommtools`? I don't want to make my users have to install the whole `openmm_orion` repo to use this, so my only alternative at present is to duplicate the code.

(Or, I can do a pull request to move the code here if you want...)

**Comment by davidlmobley** [comment]
Of course, the other fix to the specific issue is just to fix PDBFixer so it retains bond orders and aromaticity if they are present. I would imagine the authors would be receptive to a PR that does this...

**Comment by nividic** [comment]
@jchodera would be possible to update the packmol version available in omnia please?

**Comment by jchodera** [comment]
We can do that! @lnaden or @andrrizzi: Can you help? We may need to take advantage of the scheme for defining updated epochs for version numbering since we need to switch from date-based versions to version numbers (if we haven't already done that).
