### ISSUE TITLE
How to specify the packmol version in conda

### ISSUE THREAD

**Issue by nividic** [oess/oeommtools#27]
@jchodera I need to manually specify the packmol installation version in Orion. The version in omnia is 1!17.221. I locally try to install packmol like:
```
conda install packmol=1!17.221 -c omnia 
conda install packmol=17.221 -c ominia
```
and many others but they do not work. 
Can you help me with that please

**Comment by nividic** [comment]
Ok ```conda install packmol="*17.221" -c conda``` seems to work

**Comment by jchodera** [comment]
In bash, you would need to backslash-protect the `!` character:
```bash
conda install packmol=1\!17.221 -c omnia
```
It's still odd that just using `17.221` doesn't work. I'll do some more digging.

@lnaden may have more insight into how [version epochs](http://legacy.python.org/dev/peps/pep-0440/#version-epochs) are meant to work with conda.
