### ISSUE TITLE
Issues round-tripping from OEMol<-> OpenMM Topology?

### ISSUE THREAD

**Issue by davidlmobley** [oess/oeommtools#30]
I heard from John Chodera that @lnaden caught some sort of issue where OEMol <-> OpenMM Topology conversion is not done correctly in some cases; an issue with some kind of bond orders? Levi, can you provide details? I think it will be critical to get this fixed quickly if indeed there is a problem, as we're headed towards using this frequently/in many places.

@nividic - do you have a test which checks to ensure that if you take an OEMol to an OpenMM topology and back, you get the same molecule? Ideally for a couple of non-trivial cases where bond orders are important?

**Comment by Lnaden** [comment]
Sure, Its an oddity I noticed in the Topology conversion code, I'll point it out in a bit

**Comment by Lnaden** [comment]
Right, so I don't know if this is just what is required for the OEMol conversion, but this seemed odd to me.

As I understand, the OpenMM `bond.order` is specifies the character of the bond, which is fine and is shown [on this block](https://github.com/oess/oeommtools/blob/master/oeommtools/utils.py#L174-L180).

However, the `bond.type` which can be any of the named bond classes `Single`, `Double`, `Tripple`, `Aromatic`, and `Amide` (or `None`) if interpreted as "If this parameter is set, automatically infer its an aromatic bond" [as shown here](https://github.com/oess/oeommtools/blob/master/oeommtools/utils.py#L187-L189) and [here](https://github.com/oess/oeommtools/blob/master/oeommtools/utils.py#L194-L195).

My problem with that is if the bond.type is in fact a single/double/triple bond marked with the `Single`, `Double`, or `Triple` class, then its not really an aromatic bond, is it? As such, if you do `openmmTop_to_oemol` -> `oemol_to_openmmTop` on a bond which started in the `openmmTop` as a `Single`, it will come back out as an OpenMM `Aromatic` in the end.

**Comment by bannanc** [comment]
It looks like this was addressed in a pull request in Dec. 2017 which was merged into master, does that mean this issue has been addressed?

**Comment by Lnaden** [comment]
Based on https://github.com/oess/oeommtools/pull/31#issuecomment-350092154

"yes"
